import React, { useEffect, useRef, useState } from 'react';
import { Undo2, Check, Play, Copy, RotateCw } from 'lucide-react';
import lynxIcon from '../assets/lynx-default.png';

export interface NoteFieldProps {
  /** Existing saved note; when non-empty the field opens in the "saved" state. */
  initialNote?: string;
  /** Human-readable timestamp for the saved note (e.g. "Mar 20, 9:35 AM EST"). */
  initialUpdatedAt?: string;
  /** True when the existing saved note was generated by Lynx (shows the regenerate action). */
  initialLynxGenerated?: boolean;
  /** Text inserted when the user taps "Generate with Lynx AI" (empty state). */
  generatedNote?: string;
  onSave?: (text: string) => void;
  onClear?: () => void;
  /** Play the saved note's audio (prototype). */
  onAudio?: () => void;
  /** Regenerate a Lynx-generated note (prototype). */
  onRefresh?: () => void;
}

const DEFAULT_GENERATED_NOTE =
  'Frisur describes the overall style/arrangement of the hair, not the hair itself — so eine schlechte Frisur means a bad haircut or styling.';

function formatTimestamp(d: Date): string {
  const date = d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  const time = d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
  const tz = new Intl.DateTimeFormat('en-US', { timeZoneName: 'short' })
    .formatToParts(d)
    .find((p) => p.type === 'timeZoneName')?.value;
  return tz ? `${date}, ${time} ${tz}` : `${date}, ${time}`;
}

export const NoteField: React.FC<NoteFieldProps> = ({
  initialNote = '',
  initialUpdatedAt,
  initialLynxGenerated = false,
  generatedNote = DEFAULT_GENERATED_NOTE,
  onSave,
  onClear,
  onAudio,
  onRefresh,
}) => {
  const [savedText, setSavedText] = useState(initialNote.trim());
  const [updatedAt, setUpdatedAt] = useState(initialUpdatedAt ?? '');
  const [draft, setDraft] = useState(initialNote);
  const [editing, setEditing] = useState(false);
  /** Whether the current saved note originated from "Generate with Lynx AI". */
  const [lynxGenerated, setLynxGenerated] = useState(initialLynxGenerated);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const mode: 'empty' | 'focus' | 'saved' = editing
    ? 'focus'
    : savedText !== ''
      ? 'saved'
      : 'empty';

  useEffect(() => {
    if (editing) {
      const el = textareaRef.current;
      if (el) {
        el.focus();
        const end = el.value.length;
        el.setSelectionRange(end, end);
      }
    }
  }, [editing]);

  const beginEditing = () => {
    setDraft(savedText);
    setEditing(true);
  };

  const handleSave = () => {
    const next = draft.trim();
    setSavedText(next);
    if (next !== '') {
      setUpdatedAt(formatTimestamp(new Date()));
      onSave?.(next);
    } else {
      setUpdatedAt('');
      setLynxGenerated(false); // cleared → a future manual note isn't Lynx-generated
      onClear?.();
    }
    setEditing(false);
  };

  const handleCopy = () => {
    navigator.clipboard?.writeText(savedText).catch(() => {});
  };

  /** Regenerate the Lynx note (prototype: re-seeds with the generated text + new timestamp). */
  const handleRefresh = () => {
    setSavedText(generatedNote.trim());
    setUpdatedAt(formatTimestamp(new Date()));
    onRefresh?.();
  };

  /** X clears the note entirely and resets the field to the empty state. */
  const handleClear = () => {
    setDraft('');
    setSavedText('');
    setUpdatedAt('');
    setLynxGenerated(false);
    setEditing(false);
    onClear?.();
  };

  const handleGenerate = () => {
    setDraft(generatedNote);
    setLynxGenerated(true);
    setEditing(true);
  };

  if (mode === 'focus') {
    return (
      <div className="note-field note-field--focus">
        <div className="note-field__box note-field__box--focus">
          <textarea
            ref={textareaRef}
            className="note-field__textarea"
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            placeholder="Add your note here ..."
            aria-label="Note"
            rows={1}
          />
          <div className="note-field__actions">
            <button
              type="button"
              className="note-field__action note-field__action--cancel"
              aria-label="Clear note"
              onClick={handleClear}
            >
              <Undo2 size={16} aria-hidden />
            </button>
            <button
              type="button"
              className="note-field__action note-field__action--save"
              aria-label="Save note"
              onClick={handleSave}
            >
              <Check size={16} aria-hidden />
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (mode === 'saved') {
    return (
      <div className="note-field note-field--saved">
        <div className="note-field__box note-field__box--saved">
          <button
            type="button"
            className="note-field__saved-main"
            onClick={beginEditing}
            aria-label="Edit note"
          >
            <span className="note-field__saved-header">
              <span className="note-field__saved-header-label">Last Updated</span>
              <span className="note-field__saved-header-time">{updatedAt}</span>
            </span>
            <span className="note-field__saved-body">{savedText}</span>
          </button>
          <div className="note-field__saved-actions">
            <button
              type="button"
              className="note-field__saved-action"
              aria-label="Play note audio"
              onClick={() => onAudio?.()}
            >
              <Play size={16} aria-hidden />
            </button>
            <button
              type="button"
              className="note-field__saved-action"
              aria-label="Copy note"
              onClick={handleCopy}
            >
              <Copy size={16} aria-hidden />
            </button>
            {/* Regenerate — only for Lynx-generated notes. */}
            {lynxGenerated && (
              <button
                type="button"
                className="note-field__saved-action"
                aria-label="Regenerate note"
                onClick={handleRefresh}
              >
                <RotateCw size={16} aria-hidden />
              </button>
            )}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="note-field note-field--empty">
      <button
        type="button"
        className="note-field__box note-field__box--empty"
        onClick={beginEditing}
        aria-label="Add a note"
      >
        <span className="note-field__placeholder">Add your note here ...</span>
      </button>
      <button type="button" className="note-field__generate" onClick={handleGenerate}>
        <img src={lynxIcon} alt="" className="note-field__generate-icon" aria-hidden />
        <span>Generate with Lynx AI</span>
      </button>
    </div>
  );
};
